[package]
name = "chain-slicer"
version = "1.0.3"
edition = "2021"
authors = ["Fred Kyung-jin Rezeau <hello@kyungj.in>"]
description = "A Stellar smart contract implementing a trustless geometry puzzle game verified by zero-knowledge proofs"
repository = "https://github.com/fredericrezeau/xray-games"
publish = false

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
common = { path = "../common" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
